coverage:
  precision: 2
  round: down

  status:
    patch:
      default:
        enabled: yes
        target: 90%

comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
  behavior: default
